"""Database package."""

from database.connection import DB_PATH, get_connection, get_db_path

__all__ = [
    # connection
    "DB_PATH",
    "get_connection",
    "get_db_path",
    # schema
    "init_db",
    # feed
    "cleanup_old_cached_videos",
    "cleanup_orphaned_cached_videos",
    "cleanup_stale_watched_channels",
    "get_all_watched_channels",
    "get_cached_channel_ids",
    "get_channels_metadata",
    "get_errored_channel_ids",
    "get_feed_count_for_channels",
    "get_feed_for_channels",
    "get_subscription_by_channel_id",
    "get_watched_channels_with_status",
    "update_channel_metadata",
    "update_fetch_status",
    "upsert_cached_videos",
    "upsert_watched_channels",
    # settings
    "get_settings_row",
    "is_basic_auth_enabled",
    "set_basic_auth_enabled",
    "update_settings",
    # sites
    "add_credential",
    "create_site",
    "delete_credential",
    "delete_site",
    "get_all_sites",
    "get_credential",
    "get_enabled_sites",
    "get_site",
    "get_site_by_extractor",
    "update_site",
    # users
    "count_admin_users",
    "count_admins",
    "count_users",
    "create_admin",
    "create_user",
    "delete_admin",
    "delete_user",
    "get_admin_by_id",
    "get_admin_by_username",
    "get_all_admins",
    "get_all_users",
    "get_user_by_id",
    "get_user_by_username",
    "has_any_admin",
    "has_any_user",
    "update_admin_last_login",
    "update_admin_password",
    "update_user",
    "update_user_last_login",
    "update_user_password",
]
from database.repositories.feed import (
    cleanup_old_cached_videos,
    cleanup_orphaned_cached_videos,
    cleanup_stale_watched_channels,
    get_all_watched_channels,
    get_cached_channel_ids,
    get_channels_metadata,
    get_errored_channel_ids,
    get_feed_count_for_channels,
    get_feed_for_channels,
    get_subscription_by_channel_id,
    get_watched_channels_with_status,
    update_channel_metadata,
    update_fetch_status,
    upsert_cached_videos,
    upsert_watched_channels,
)
from database.repositories.settings import (
    get_settings_row,
    is_basic_auth_enabled,
    set_basic_auth_enabled,
    update_settings,
)
from database.repositories.sites import (
    add_credential,
    create_site,
    delete_credential,
    delete_site,
    get_all_sites,
    get_credential,
    get_enabled_sites,
    get_site,
    get_site_by_extractor,
    update_site,
)
from database.repositories.users import (
    count_admin_users,
    count_admins,
    count_users,
    create_admin,
    create_user,
    delete_admin,
    delete_user,
    get_admin_by_id,
    get_admin_by_username,
    get_all_admins,
    get_all_users,
    get_user_by_id,
    get_user_by_username,
    has_any_admin,
    has_any_user,
    update_admin_last_login,
    update_admin_password,
    update_user,
    update_user_last_login,
    update_user_password,
)
from database.schema import init_db
